[package]
name = "rasypt-lite-lib"
version.workspace = true
edition.workspace = true
description = "Password-based encryption with PBEWithHMACSHA512AndAES_256 and SM-compliant algorithms"
authors.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/czyczk/rasypt_lite"
homepage = "https://github.com/czyczk/rasypt_lite"
keywords = ["jasypt", "encryption", "sm3", "sm4", "secret"]
categories = ["cryptography", "algorithms", "authentication"]

[dependencies]
aes.workspace = true
cbc.workspace = true
ghash.workspace = true
hmac.workspace = true
pbkdf2.workspace = true
sha2.workspace = true
sm3.workspace = true
sm4.workspace = true
subtle.workspace = true
strum = { workspace = true, features = ["derive"] }
rand = { workspace = true, features = ["default", "thread_rng"] }
base64.workspace = true
unicode-normalization.workspace = true
zeroize.workspace = true
thiserror.workspace = true
